import re

# Exact raw markdown response generated by Step 4
RAW_TEXT_EXAMPLE = """Based on the provided sources, retrieval-augmented generation (RAG) automates literature reviews through the following process:

* **Input and Primary Objective:** The system is designed to automatically generate literature reviews using only PDF files as the input [1]. RAG provides a modular approach that allows the system to integrate this external knowledge (the PDF documents) without needing to increase the internal capacity of the Large Language Model (LLM) [3].
* **Model Integration:** The automation is implemented by combining RAG with a Large Language Model, such as GPT-3.5-turbo [1][2]. 
* **Evaluation and Performance:** In experimental applications using the SciTLDR dataset, the RAG-based LLM approach (specifically GPT-3.5-turbo) outperformed other natural language processing methods [1][2]. When evaluated using ROUGE scores, the RAG LLM system achieved the highest ROUGE-1 score of 0.364, performing better than a transformer model (Simple T5) and a frequency-based method (spaCy) [2].
* **User Interface:** To make the automated system accessible, a graphical user interface can be created for the final LLM-based RAG system [2].

**Sufficient Information Warning:** 
The retrieved papers do not provide sufficient information to explain the specific technical steps of the RAG pipeline for this task, such as how the PDF files are chunked, embedded, retrieved, or prompted during the literature review generation process."""


def extract_claims_from_markdown(text: str):
    """
    Splits markdown-formatted answers (bullets, bold labels, multi-sentence items)
    into distinct claim units with their associated citation indices.
    
    Protects against false splits:
    - Decimals like '0.364' or 'GPT-3.5-turbo'
    - Abbreviations like 'al.', 'e.g.'
    - Inline citations '[1]', '[1][2]'
    """
    claims = []
    
    # Split text into lines/paragraphs
    lines = text.split("\n")
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        # If the line contains no citation brackets, it's an uncited intro/outro
        if not re.search(r"\[\d+\]", line):
            continue
            
        # Strip leading markdown bullet markers: '*', '-', '1.'
        content = re.sub(r"^[*\-•]\s+", "", line)
        content = re.sub(r"^\d+\.\s+", "", content)
        
        # Split sentences within the bullet.
        # Rule: Split on (. or ! or ?) followed by a space and an uppercase letter,
        # BUT NOT if preceded by common abbreviations or decimal digits.
        # Negative lookbehind: (?<!\d)(?<!\b(?:e\.g|i\.e|et al|vs|dr|fig))\.(?!\d)
        
        # We replace sentence-ending periods with a unique delimiter
        # Step 1: Temporarily replace citations after period (e.g. '. [1]' or '.[1]')
        # Notice: sentences may end with: 'input [1]. RAG provides' OR 'methods [1][2]. When evaluated'
        sentence_end_pattern = r"(?<=[.!?])\s+(?=[A-Z0-9*])"
        raw_sentences = re.split(sentence_end_pattern, content)
        
        for s in raw_sentences:
            s = s.strip()
            if not s:
                continue
                
            # Extract citations: e.g. [1], [2] -> [1, 2]
            citations = [int(m) for m in re.findall(r"\[(\d+)\]", s)]
            if not citations:
                # Part of bullet without citation
                continue
                
            # Clean claim text:
            # 1. Remove citations '[1]'
            # 2. Remove leading bold label if present, e.g. '**Input and Primary Objective:**'
            claim_text = re.sub(r"\[\d+\]", "", s).strip()
            
            # Optional: strip leading markdown bold category header for cleaner entailment prompt
            # e.g., '**Input and Primary Objective:** The system...' -> 'The system...'
            claim_statement = re.sub(r"^\*\*[^*]+:\*\*\s*", "", claim_text).strip()
            if not claim_statement:
                claim_statement = claim_text
                
            claims.append({
                "original_bullet_line": line,
                "raw_sentence": s,
                "claim_statement": claim_statement,
                "citations": sorted(list(set(citations)))
            })
            
    return claims

if __name__ == "__main__":
    results = extract_claims_from_markdown(RAW_TEXT_EXAMPLE)
    print(f"Total Claims Extracted: {len(results)}\n")
    for i, item in enumerate(results, 1):
        print(f"--- Claim {i} ---")
        print(f"Citations Target : {item['citations']}")
        print(f"Claim Statement  : \"{item['claim_statement']}\"")
        print(f"Raw Snippet      : \"{item['raw_sentence']}\"")
        print()
